modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="BSD-3-Clause"

issueTrackerURL="" #optional

[[mods]] #mandatory

modId="forgecef" #mandatory

version="1.2.0" #mandatory

displayName="MCEF" #mandatory

displayURL="https://github.com/goldorak85/mcef-forge" #optional

logoFile= "" #optional

credits="" #optional

authors="Mysticpasta1, WaterPicker, Montoyo, javaarchive, Goldorak85" #optional

description='''
'''

[[dependencies.forgecef]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.forgecef]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
